# THE PORT THAT THIS PROXY WILL BIND TO FOR GRPC (MUST BE UNIQUE)
GRPC_PORT: 5001

# SAME AS DEFINED IN VELOCITY.TOML
DUELS_SERVER_NAME: "duels"
# SAME AS DEFINED IN BACKEND SPIGOT PLUGIN'S CONFIG.YML
DUELS_GRPC_IP: "127.0.0.1"
DUELS_GRPC_PORT: 5002

# NAME MUST BE SAME AS ONE DEFINED IN VELOCITY.TOML & ON WAGER PLUGIN'S CONFIG.YML
SERVERS:
  - NAME: "factions"
    IP: "127.0.0.1"
    PORT: 5003
  - NAME: "skyblock"
    IP: "127.0.0.1"
    PORT: 5004